### ISSUE TITLE
Back button in hamburger on desktop has wrong hover style

### ISSUE THREAD

**Issue by vdua** [hlxsites/nedbank#205]
The back button is missing the following styles on hover
```css
{
color: white;
cursor: pointer;
}
```
<img width="649" alt="image" src="https://user-images.githubusercontent.com/2097597/232654757-67a098c8-8a56-415e-ba48-73c6b4c887ab.png">
